### ISSUE TITLE
Causes 1.7.10 forge to crash instantly when launching

### ISSUE THREAD

**Issue by KingBlueBrine** [dogboy21/serializationisbad#84] opened 2024-03-17 18:03 UTC
When launching a 1.7.10 pack from the mc launcher it will wait a few seconds then crash then giving Error Code: 1
When this mod is removed mc boots normally without issues. This same crash has happened on different 1.7.10 modpacks that don't share any mods.
The .latest log txt file has been attached after the crash.
[latest.log](https://github.com/dogboy21/serializationisbad/files/14628343/latest.log)

**Comment by dogboy21** [comment] 2024-03-17 18:05
Duplicate of #83

Please update the SerializationIsBad mod to [version 1.5.2](https://www.curseforge.com/minecraft/mc-mods/serializationisbad/files/5187152)

**Comment by KingBlueBrine** [comment] 2024-03-17 18:06
aight, my bad

**Comment by dogboy21** [comment] 2024-03-17 19:13
No problem! :)
Feel free to reopen, if you still need assistance.

**Closed as completed by dogboy21** 2024-03-17 19:13 UTC
