### ISSUE TITLE
processing of -javaagent failed

### ISSUE THREAD

**Issue by Autissima** [dogboy21/serializationisbad#31] opened 2023-07-30 10:46 UTC
Similar to #29 but I am on Fabric

```
Starting server...
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at io.dogboy.serializationisbad.core.SerializationIsBad.<clinit>(SerializationIsBad.java:14)
        at io.dogboy.serializationisbad.agent.SerializationIsBadAgent.premain(SerializationIsBadAgent.java:11)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 8 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at open/src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
```

With this launch command:

`java -Xms6G -Xmx6G -javaagent:/home/opc/AstralSpace/serialbad.jar [...] server.jar --nogui`

Is the path of my javaagent just malformed, or is it misplaced?

Minecraft 1.18.2 with Fabric Loader 0.14.14, running on Oracle Linux

**Comment by dogboy21** [comment] 2023-07-30 11:20
Duplicate of #3
We're already looking into this one

**Closed by dogboy21** 2023-07-30 11:20 UTC
